Update styles.css
webex/react-widgets pull request #1170
Opened 2021-06-22 21:02 UTC by chetangoel01

2021-06-23 17:25 UTC, taymoork2 requested changes
Can you add these back in and see if it still works?
I think leaving out flex might break with browsers that don't use/understand `-webkit-box` however i can't find documentation that about `-webkit-box`'s browser compatibility

2021-06-23 17:25 UTC, taymoork2 commented on packages/node_modules/@webex/widget-roster/src/styles.css
> +  display: -webkit-box;
```suggestion
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
```

2021-06-23 17:25 UTC, taymoork2 commented on packages/node_modules/@webex/widget-roster/src/styles.css
> +  display: -webkit-box;
```suggestion
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
```

2021-06-23 19:02 UTC, lalli-flores requested changes
Can you make sure to review our [Git commit guidelines](https://github.com/webex/react-widgets/blob/master/CONTRIBUTING.md#git-commit-guidelines)?

Commits are very important because they translate into the [literal changelog](https://github.com/webex/react-widgets/blob/master/CHANGELOG.md) that customers use to understand what changed in a version

2021-06-24 19:37 UTC, taymoork2 commented
Closing this PR since origin of this branch is not @chetangoel01's fork

2021-06-24 19:37 UTC, closed without merging