fix(dialpadissue): fixed focus on search input
webex/react-widgets pull request #1334
Opened 2023-08-29 13:33 UTC by briyadav

[](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-449693)

Dialpad: Currently, shift-tab from the number key goes to the previous number in numerical order. When shift - tab from any number button, it should go back to the search field.

2023-08-29 13:53 UTC, akulakum approved these changes

2023-08-29 14:04 UTC, Waseemraj requested changes

2023-08-29 14:04 UTC, Waseemraj commented on packages/node_modules/@webex/widget-number-pad/src/NumberPad.tsx
> +    const NUMBER_PAD_FOCUSSED = 'NumberPadFocused';
Make it NUMBER_PAD_FOCUSED

2023-08-29 14:04 UTC, Waseemraj commented on packages/node_modules/@webex/widget-number-pad/src/NumberPad.tsx
> +            localStorage.setItem(NUMBER_PAD_FOCUSSED, JSON.stringify(true));
Make it NUMBER_PAD_FOCUSED everywhere

2023-08-29 14:09 UTC, akulakum reviewed
“Due to the changes in the code, the key press event ‘Enter’ is not working on the dialpad.”

2023-08-30 07:16 UTC, ravicra2 approved these changes

2023-08-31 04:15 UTC, Waseemraj commented on packages/node_modules/@webex/widget-number-pad/src/NumberPad.tsx
> +        if (event.key === "Tab" && event.shiftKey) {
Can we make "Tab" as constant please?

2023-08-31 04:17 UTC, Waseemraj approved these changes

2023-08-31 04:17 UTC, Waseemraj commented
One minor comment, please take care of them in next PR

2023-08-31 04:40 UTC, briyadav commented on packages/node_modules/@webex/widget-number-pad/src/NumberPad.tsx
> +        if (event.key === "Tab" && event.shiftKey) {
Sure

2023-08-31 10:12 UTC, merged