fix(react-widgets): snapshot test fix
webex/react-widgets pull request #1445
Opened 2024-10-23 14:56 UTC by Kesari3008

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-559078 

<img width="504" alt="Screenshot 2024-10-23 at 8 09 05 PM" src="https://github.com/user-attachments/assets/39e5f357-c4d9-4b9b-a0c0-d5362e9d5427">
<img width="496" alt="Screenshot 2024-10-23 at 8 09 18 PM" src="https://github.com/user-attachments/assets/6dd4e4b6-985d-4c03-b62c-6af8fd1f5194">
<img width="494" alt="Screenshot 2024-10-23 at 8 09 47 PM" src="https://github.com/user-attachments/assets/071a39b9-9c5a-4a49-a018-029e3f18a994">
<img width="1037" alt="Screenshot 2024-10-23 at 8 14 36 PM" src="https://github.com/user-attachments/assets/5dccf4cb-66f3-4b6d-91a4-050521a48130">

2024-10-24 09:10 UTC, sreenara requested changes
Please update the description with the list of tests done for reference in the future.
Also, looks like the unit tests and linting are failing. Could we check why this is happening.
Should we also make the browser tests optional as this needs to be completed in the future?

2024-10-25 05:52 UTC, Shreyas281299 commented on package.json
> +    "react": "^18.3.1",
```suggestion
    "react": "*18.3.1",
```
I think this a decision that we can take, using asterisk will make our components more reliable as no automatic upgrade will happen.

2024-10-25 05:54 UTC, Shreyas281299 approved these changes
Please update the description of PR to say 'React version upgrade'.

2024-10-25 06:56 UTC, sreenara approved these changes

2024-10-25 07:32 UTC, merged